name: vex
base: core22
adopt-info: vex
summary: A blazingly fast, hackable linter
description: >
  vex is a hackable linter, intended to act as an enforcer for subjective, project-local style preferences.
  Taking input of a set of Starlark scripts which express style rules, it scans the project directories to find style problems.
grade: stable
confinement: strict

apps:
  hello:
    command: vex

parts:
  vex:
    source: https://github.com/TheSignPainter98/vex.git
    plugin: rust
