name: vex # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A blazingly fast, hackable linter
description: >
  vex is a hackable linter, intended to act as an enforcer for subjective, project-local style preferences.
  Taking input of a set of Starlark scripts which express style rules, it scans the project directories to find style problems.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hello:
    command: vex

parts:
  vex:
    # See 'snapcraft plugins'
    source: .
    plugin: rust
