name: Deploy docs site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.40'

      - name: Source cargo environment
        run: |
          [[ -f ~/.cargo/env ]] && source ~/.cargo/env || true

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          default: true
          components: clippy, rustfmt

      - name: Install linkcheck
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-linkcheck

      - run: mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
