name: woke
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
